var gameConfig = window.config || {};

gameConfig.imgs = [{
		id: "a",
		src: "img/a.png"
	}, {
		id: "h",
		src: "img/h.png"
	}, {
		id: "chinese",
		src: "img/chinese.png"
	}, {
		id: "english",
		src: "img/english.png"
	}, {
		id: "logo",
		src: "img/logo.png"
	}, {
		id: "logoE",
		src: "img/logo_en.png"
	}, {
		id: "bg",
		src: "img/bg_240.png"
	}, {
		id: "cd",
		src: "img/cd.png"
	}, {
		id: "num",
		src: "img/num.png"
	}, {
		id: "dm",
		src: "img/dm.png"
	}, {
		id: "jiafen",
		src: "img/jiafen.png"
	}, {
		id: "jiafenE",
		src: "img/jiafen_en.png"
	}, {
		id: "jiantou",
		src: "img/jiantou.png"
	}, {
		id: "life_1",
		src: "img/life_1.png"
	}, {
		id: "life_2",
		src: "img/life_2.png"
	}, {
		id: "ren",
		src: "img/ren.png"
	}, {
		id: "shengzixiaoguo",
		src: "img/shengzixiaoguo.png"
	}, {
		id: "tishi",
		src: "img/tishi.png"
	}, {
		id: "tishiE",
		src: "img/tishi_en.png"
	}, {
		id: "zhuzi_y",
		src: "img/zhuzi_y.png"
	}, {
		id: "http://www.wenzhangku.com/weixin/mingxuanyixian",
		src: "img/zhuzi_z.png"
	}, {
		id: "notice",
		src: "img/notice.png"
	}, {
		id: "noticeE",
		src: "img/notice_en.png"
	}, {
		id: "han1",
		src: "img/img036.png"
	}, {
		id: "han2",
		src: "img/img037.png"
	}, {
		id: "mingzhong",
		src: "img/mingzhong.png"
	}, {
		id: "mingzhongE",
		src: "img/mingzhong_en.png"
	}, {
		id: "start",
		src: "img/start.png"
	}, {
		id: "startE",
		src: "img/start_en.png"
	}, {
		id: "more",
		src: "img/more.png?d"
	}, {
		id: "moreE",
		src: "img/more.png"
	}, {
		id: "back",
		src: "img/back.png?dd"
	}, {
		id: "backE",
		src: "img/back.png"
	}, {
		id: "retry",
		src: "img/retry.png"
	}, {
		id: "retryE",
		src: "img/retry_en.png"
	}, {
		id: "isexit",
		src: "img/isexit.png"
	}, {
		id: "isexitE",
		src: "img/isexit.png"
	}, {
		id: "intro",
		src: "img/intro.png"
	}, {
		id: "score",
		src: "img/score.png"
	}, {
		id: "scoreE",
		src: "img/score_en.png"
	}, {
		id: "Hscore",
		src: "img/Hscore.png"
	}, {
		id: "HscoreE",
		src: "img/Hscore_en.png"
	}, {
		id: "zz",
		src: "img/zz.png"
	}];

gameConfig.frames = [{
					i: 0,
					sx: 12,
					sy: 1,
					width: 20,
					height: 32,
					dx: 0,
					dy: 0,
					ssx: 0,
					ssy: 0
				}, {
					i: 1,
					sx: 53,
					sy: 0,
					width: 20,
					height: 33,
					dx: 0,
					dy: 0,
					ssx: 0,
					ssy: 0
				}, {
					i: 2,
					sx: 94,
					sy: 1,
					width: 20,
					height: 32,
					dx: 0,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 3,
					sx: 135,
					sy: 3,
					width: 20,
					height: 30,
					dx: 0,
					dy: 2,
					ssx: 0,
					ssy: 0
				}, {
					i: 4,
					sx: 177,
					sy: 3,
					width: 21,
					height: 30,
					dx: 0,
					dy: 4,
					ssx: 0,
					ssy: 0
				}, {
					i: 5,
					sx: 219,
					sy: 3,
					width: 22,
					height: 30,
					dx: 2,
					dy: 4,
					ssx: 0,
					ssy: 0
				}, {
					i: 6,
					sx: 14,
					sy: 46,
					width: 24,
					height: 28,
					dx: 3,
					dy: 4,
					ssx: 0,
					ssy: 0
				}, {
					i: 7,
					sx: 45,
					sy: 49,
					width: 23,
					height: 25,
					dx: -8,
					dy: 7,
					ssx: 0,
					ssy: 0
				}, {
					i: 8,
					sx: 86,
					sy: 49,
					width: 23,
					height: 25,
					dx: -8,
					dy: 7,
					ssx: 0,
					ssy: 0
				}, {
					i: 9,
					sx: 214,
					sy: 46,
					width: 20,
					height: 28,
					dx: 2,
					dy: 5,
					ssx: 6,
					ssy: 14
				}, {
					i: 10,
					sx: 173,
					sy: 44,
					width: 20,
					height: 30,
					dx: 2,
					dy: 3,
					ssx: 6,
					ssy: 16
				}, {
					i: 11,
					sx: 132,
					sy: 42,
					width: 20,
					height: 32,
					dx: 2,
					dy: 1,
					ssx: 8,
					ssy: 16
				}, {
					i: 12,
					sx: 12,
					sy: 85,
					width: 20,
					height: 33,
					dx: 0,
					dy: 0,
					ssx: 1,
					ssy: 16
				}, {
					i: 13,
					sx: 53,
					sy: 81,
					width: 20,
					height: 36,
					dx: 0,
					dy: 0,
					ssx: 1,
					ssy: 18
				}, {
					i: 14,
					sx: 95,
					sy: 88,
					width: 20,
					height: 33,
					dx: 0,
					dy: 0,
					ssx: 1,
					ssy: 15
				}, {
					i: 15,
					sx: 136,
					sy: 90,
					width: 21,
					height: 32,
					dx: -1,
					dy: 0,
					ssx: -1,
					ssy: 15
				}, {
					i: 16,
					sx: 176,
					sy: 91,
					width: 22,
					height: 31,
					dx: -1,
					dy: -1,
					ssx: 1,
					ssy: 11
				}, {
					i: 17,
					sx: 215,
					sy: 92,
					width: 24,
					height: 31,
					dx: -2,
					dy: -1,
					ssx: 1,
					ssy: 10
				}, {
					i: 18,
					sx: 5,
					sy: 133,
					width: 29,
					height: 27,
					dx: -5,
					dy: -3,
					ssx: 2,
					ssy: 8
				}, {
					i: 19,
					sx: 41,
					sy: 133,
					width: 34,
					height: 22,
					dx: -7,
					dy: -5,
					ssx: 5,
					ssy: 5
				}, {
					i: 20,
					sx: 85,
					sy: 133,
					width: 31,
					height: 20,
					dx: -6,
					dy: -6,
					ssx: 6,
					ssy: 4
				}, {
					i: 21,
					sx: 126,
					sy: 133,
					width: 31,
					height: 20,
					dx: -6,
					dy: -6,
					ssx: 7,
					ssy: 4
				}, {
					i: 22,
					sx: 164,
					sy: 133,
					width: 34,
					height: 22,
					dx: -7,
					dy: -5,
					ssx: 0,
					ssy: 0
				}, {
					i: 23,
					sx: 210,
					sy: 133,
					width: 29,
					height: 27,
					dx: -5,
					dy: -3,
					ssx: 0,
					ssy: 0
				}, {
					i: 24,
					sx: 7,
					sy: 173,
					width: 27,
					height: 30,
					dx: -4,
					dy: -1,
					ssx: 0,
					ssy: 0
				}, {
					i: 25,
					sx: 51,
					sy: 170,
					width: 23,
					height: 34,
					dx: -2,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 26,
					sx: 95,
					sy: 170,
					width: 20,
					height: 34,
					dx: 0,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 27,
					sx: 135,
					sy: 168,
					width: 20,
					height: 34,
					dx: 0,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 28,
					sx: 178,
					sy: 164,
					width: 20,
					height: 32,
					dx: 0,
					dy: 0,
					ssx: 0,
					ssy: 0
				}, {
					i: 29,
					sx: 217,
					sy: 167,
					width: 20,
					height: 30,
					dx: 0,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 30,
					sx: 12,
					sy: 207,
					width: 20,
					height: 31,
					dx: 0,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 31,
					sx: 55,
					sy: 207,
					width: 20,
					height: 31,
					dx: 0,
					dy: 2,
					ssx: 0,
					ssy: 0
				}, {
					i: 32,
					sx: 94,
					sy: 207,
					width: 20,
					height: 31,
					dx: -2,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 33,
					sx: 132,
					sy: 209,
					width: 20,
					height: 29,
					dx: 0,
					dy: 2,
					ssx: 0,
					ssy: 0
				}, {
					i: 34,
					sx: 175,
					sy: 207,
					width: 20,
					height: 31,
					dx: 2,
					dy: 1,
					ssx: 0,
					ssy: 0
				}, {
					i: 35,
					sx: 0,
					sy: 0,
					width: 1,
					height: 1,
					dx: 0,
					dy: 0,
					ssx: 0,
					ssy: 0
				}];

// image "Here" y posititon. 
gameConfig.noticeYPosArray = [{
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}, {
					y: -1
				}, {
					y: 0
				}, {
					y: 1
				}, {
					y: 0
				}];
